@Library('propsFileReader') _

def props = loadProperties(${env.WORKSPACE} + "/misc/config.properties")

pipeline {
    agent any
    tools { nodejs "nodejs"}
    environment {
        commit_id = ''
        REGISTRY = props['REGISTRY']
    }
    stages {
        stage('Preparation') {
            steps {
                checkout scm
                script {
                    sh 'printenv'
                    commit_id = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                }
            }
        }
        stage('test') {
            agent {
                label 'nodejs'
            }
            steps {
                sh 'npm install --only=dev'
                sh 'npm test'
            }
        }
        stage('docker build/push') {
            environment {
                REGISTRY = props['REGISTRY']
                registryCredential = 'dockerhub'
            }
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        def app = docker.build("kubeiklen/docker-nodejs-demo:${commit_id}", '.')
                        app.push()
                    }
                }
            }
        }
    }
}
