@Library('propsFileReader') _

def props = readPropertiesFile('path/to/your/properties/file.properties')

pipeline {
    agent any
    tools { nodejs "nodejs"}
    environment {
        commit_id = ''
        for (prop in props) {
            "${prop.key}" : "${prop.value}"
        }
    }
    stages {
        stage('Preparation') {
            steps {
                checkout scm
                script {
                    sh 'printenv'
                    commit_id = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                }
            }
        }
        stage('test') {
            agent {
                label 'nodejs'
            }
            steps {
                sh 'npm install --only=dev'
                sh 'npm test'
            }
        }
        stage('docker build/push') {
            environment {
                registry = 'https://index.docker.io/v1/'
                registryCredential = 'dockerhub'
            }
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        def app = docker.build("kubeiklen/docker-nodejs-demo:${commit_id}", '.')
                        app.push()
                    }
                }
            }
        }
    }
}
