@Library('propsFileReader') _

def props = [:]

pipeline {
    agent any
    tools {
        nodejs "nodejs"
    }
    stages {
        stage('test') {
            agent {
                label 'nodejs'
            }
            steps {
                sh 'npm install --only=dev'
                sh 'npm test'
                script {
                     props = readPropertiesFile("${WORKSPACE}/misc/config.properties")
                }
            }
        }
        stage('docker build/push') {
            environment {
                REGISTRY = "${props['REGISTRY']}"
                REGISTRY_CREDENTIAL = "${props['REGISTRY_CREDENTIAL']}"
                commit_id = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
            }
            steps {
                script {
                    docker.withRegistry(env.REGISTRY, env.REGISTRY_CREDENTIAL) {
                        def app = docker.build("kubeiklen/docker-nodejs-demo:${env.commit_id}", '.')
                        app.push()
                    }
                }
            }
        }
    }
}